spring:
  application:
    name: webflux-demo-annotation
  r2dbc:
    url: r2dbc:mysql://192.168.144.1:3306/test
    username: root
    password: root
    pool:
      enabled: false

logging:
  level:
    root: INFO
    com.example.webfluxdemoannotation: DEBUG # 패키지 로그
    org.springframework.r2dbc.core: DEBUG # Spring R2DBC가 실행하는 SQL 로그
    io.r2dbc.spi.ConnectionFactory: DEBUG # SQL 로그 출력을 위해 사용하는 ConnectionFactory wrapping 로그
    dev.miku.r2dbc.mysql: DEBUG # R2DBC MySQL 드라이버 로그

# swaager (springdoc)
springdoc:
#  packages-to-scan: com.example
  api-docs:
    path: /api-docs # Swagger JSON 문서를 제공하는 엔드포인트 경로
  swagger-ui:
#    path: /swagger-ui.html #Swagger UI 페이지의 접근 경로
    groups-order: DESC
    tags-sorter: alpha   # 태그 이름 기준 API 정렬 - 가능한 값: alpha(알파벳순), method(GET, POST 순 등)
    operations-sorter: method  # 엔드포인트 정렬 method/alpha (HTTP 메서드 순서로 정렬)
#    disable-swagger-default-url: true
#    display-request-duration: true
#    defaultModelsExpandDepth: 2
#    defaultModelExpandDepth: 2
#  show-actuator: true
#  default-consumes-media-type: application/json # 기본 요청, 응답 형태를 JSON으로 설정
#  default-produces-media-type: application/json
#  writer-with-default-pretty-printer: true
#  model-and-view-allowed: true
#  paths-to-match:
#    - /**